import { internalMutation } from "./_generated/server";

/**
 * Seed the catalog. Idempotent: no-ops if books already exist.
 * Run: npx convex run seed:run
 * All books seed as "available" — status is transactionally maintained and
 * only ever changes inside borrow/return mutations.
 */

const BOOKS = [
  {"title":"Muhammad: His Life Based on the Earliest Sources","author":"Martin Lings","publisher":"Islamic Texts Society","year":1983,"topic":"seerah","language":"en","audience":"adult","tint":"--tint-slate","staffPick":true,"isNew":false,"description":"A cornerstone contemporary Seerah drawn directly from the earliest Arabic sources. Read slowly; it rewards patience.","status":"available"},
  {"title":"The Sealed Nectar","author":"Safi-ur-Rahman al-Mubarakpuri","publisher":"Darussalam","year":1996,"topic":"seerah","language":"en","audience":"adult","tint":"--tint-forest","staffPick":false,"isNew":false,"description":"The award-winning modern Seerah, thorough and accessible. A default starting point in many masjid libraries.","status":"available"},
  {"title":"In the Footsteps of the Prophet","author":"Tariq Ramadan","publisher":"Oxford University Press","year":2007,"topic":"seerah","language":"en","audience":"adult","tint":"--tint-aubergine","staffPick":true,"isNew":false,"description":"Lessons drawn from the Prophet's life for present-day readers, with a reflective tone rather than pure biography.","status":"available"},
  {"title":"When the Moon Split","author":"Safi-ur-Rahman al-Mubarakpuri","publisher":"Darussalam","year":1998,"topic":"seerah","language":"en","audience":"teen","tint":"--tint-teal","staffPick":false,"isNew":false,"description":"A briefer, more narrative Seerah suited to teens and adults new to the tradition.","status":"available"},
  {"title":"The Study Quran","author":"Seyyed Hossein Nasr (ed.)","publisher":"HarperOne","year":2015,"topic":"quran","language":"bilingual","audience":"adult","tint":"--tint-ink","staffPick":true,"isNew":true,"description":"A comprehensive scholarly translation with running commentary drawn from classical tafsir traditions.","status":"available"},
  {"title":"The Message of the Qur'an","author":"Muhammad Asad","publisher":"Book Foundation","year":1980,"topic":"quran","language":"bilingual","audience":"adult","tint":"--tint-oxblood","staffPick":false,"isNew":false,"description":"A widely-read English rendering with extensive footnotes reflecting Asad's rationalist approach.","status":"available"},
  {"title":"Tafsir Ibn Kathir (Abridged, 10 vols.)","author":"Safi-ur-Rahman al-Mubarakpuri (ed.)","publisher":"Darussalam","year":2003,"topic":"quran","language":"en","audience":"adult","tint":"--tint-mustard","staffPick":true,"isNew":false,"description":"The classical tafsir in abridged English translation. Reference volume the borrowing desk will help you locate.","status":"available"},
  {"title":"Reflecting on the Names of Allah","author":"Jinan Yousef","publisher":"Kube Publishing","year":2020,"topic":"quran","language":"en","audience":"adult","tint":"--tint-teal","staffPick":false,"isNew":true,"description":"A contemplative walk through the Divine Names, structured for daily reading.","status":"available"},
  {"title":"Reliance of the Traveller","author":"Ahmad ibn Naqib al-Misri (tr. N. H. M. Keller)","publisher":"Amana","year":1994,"topic":"fiqh","language":"bilingual","audience":"adult","tint":"--tint-slate","staffPick":true,"isNew":false,"description":"The classical Shafi'i manual with parallel Arabic and annotated English. Reference — reads with a companion.","status":"available"},
  {"title":"Purification of the Heart","author":"Hamza Yusuf","publisher":"Sandala","year":2004,"topic":"fiqh","language":"en","audience":"adult","tint":"--tint-forest","staffPick":true,"isNew":false,"description":"Translation and commentary on Imam al-Mawlud's poem on tazkiyah — spiritual diseases of the heart and their cures.","status":"available"},
  {"title":"Being Muslim","author":"Asad Tarsin","publisher":"Sandala","year":2015,"topic":"fiqh","language":"en","audience":"adult","tint":"--tint-aubergine","staffPick":false,"isNew":false,"description":"A practical primer on Islamic beliefs, practice, and spirituality for readers new to the tradition.","status":"available"},
  {"title":"The Content of Character","author":"Shaykh al-Amin Ali Mazrui","publisher":"Sandala","year":2005,"topic":"fiqh","language":"bilingual","audience":"adult","tint":"--tint-oxblood","staffPick":false,"isNew":false,"description":"A collection of prophetic sayings on ethics with parallel Arabic and English translations.","status":"available"},
  {"title":"Reclaim Your Heart","author":"Yasmin Mogahed","publisher":"FB Publishing","year":2012,"topic":"fiqh","language":"en","audience":"adult","tint":"--tint-terracotta","staffPick":false,"isNew":false,"description":"Essays on faith, love, loss, and returning attention to the eternal — widely read among younger adults.","status":"available"},
  {"title":"Lost Islamic History","author":"Firas Alkhateeb","publisher":"Hurst","year":2014,"topic":"history","language":"en","audience":"adult","tint":"--tint-mustard","staffPick":true,"isNew":false,"description":"A single-volume narrative history of Muslim civilizations from the Prophet ﷺ to the twentieth century.","status":"available"},
  {"title":"Destiny Disrupted","author":"Tamim Ansary","publisher":"PublicAffairs","year":2009,"topic":"history","language":"en","audience":"adult","tint":"--tint-terracotta","staffPick":false,"isNew":false,"description":"World history as it looks from the middle of the Muslim world outward — a valuable corrective to Eurocentric surveys.","status":"available"},
  {"title":"The Great Theft: Wrestling Islam from the Extremists","author":"Khaled Abou El Fadl","publisher":"HarperOne","year":2005,"topic":"history","language":"en","audience":"adult","tint":"--tint-ink","staffPick":false,"isNew":false,"description":"A scholar of Islamic law argues for reclaiming the mainstream tradition from puritanical readings.","status":"available"},
  {"title":"Amina's Voice","author":"Hena Khan","publisher":"Salaam Reads","year":2017,"topic":"youth","language":"en","audience":"child","tint":"--tint-teal","staffPick":true,"isNew":false,"description":"A Pakistani-American middle-schooler finds her voice — and her community — after a devastating loss.","status":"available"},
  {"title":"The Proudest Blue","author":"Ibtihaj Muhammad & S. K. Ali","publisher":"Little, Brown","year":2019,"topic":"youth","language":"en","audience":"child","tint":"--tint-slate","staffPick":true,"isNew":false,"description":"A picture book about a young girl's first day of school with her older sister in a beautiful blue hijab.","status":"available"},
  {"title":"Once Upon an Eid","author":"S. K. Ali & Aisha Saeed (eds.)","publisher":"Amulet","year":2020,"topic":"youth","language":"en","audience":"teen","tint":"--tint-forest","staffPick":false,"isNew":true,"description":"An anthology of Eid stories by fifteen Muslim writers — funny, tender, everyday and celebratory.","status":"available"},
  {"title":"Yasmin the Explorer","author":"Saadia Faruqi","publisher":"Picture Window Books","year":2018,"topic":"youth","language":"en","audience":"child","tint":"--tint-mustard","staffPick":false,"isNew":false,"description":"An early-reader series about a curious Pakistani-American girl. The whole set is on the kids' shelf.","status":"available"},
  {"title":"The Gift of Ramadan","author":"Rabiah York Lumbard","publisher":"Albert Whitman","year":2019,"topic":"youth","language":"en","audience":"child","tint":"--tint-aubergine","staffPick":false,"isNew":false,"description":"A tender picture book about a young girl attempting her first fast.","status":"available"},
  {"title":"The Butterfly Mosque","author":"G. Willow Wilson","publisher":"Grove Atlantic","year":2010,"topic":"contemp","language":"en","audience":"adult","tint":"--tint-terracotta","staffPick":true,"isNew":false,"description":"A memoir of conversion and cross-cultural marriage, told with warmth and precision.","status":"available"},
  {"title":"The Bad Muslim Discount","author":"Syed M. Masood","publisher":"Doubleday","year":2021,"topic":"contemp","language":"en","audience":"adult","tint":"--tint-oxblood","staffPick":false,"isNew":true,"description":"A generous, funny novel about two Muslim families in America, and about faith held with a light hand.","status":"available"},
  {"title":"The Beauty of Your Face","author":"Sahar Mustafah","publisher":"W. W. Norton","year":2020,"topic":"contemp","language":"en","audience":"adult","tint":"--tint-ink","staffPick":false,"isNew":false,"description":"A Palestinian-American principal's story, told across two timelines — recent and everyday, taut and searching.","status":"available"},
  {"title":"Salt Houses","author":"Hala Alyan","publisher":"Mariner","year":2017,"topic":"contemp","language":"en","audience":"adult","tint":"--tint-forest","staffPick":true,"isNew":false,"description":"A multi-generational novel following one Palestinian family through displacement, in luminous, unhurried prose.","status":"available"},
  {"title":"The Faith of Others","author":"Homayra Ziad","publisher":"Interfaith Press","year":2023,"topic":"contemp","language":"en","audience":"adult","tint":"--tint-teal","staffPick":false,"isNew":true,"description":"Essays on Muslim interfaith engagement in the American century, from a scholar-practitioner working in the Triangle.","status":"available"},
  {"title":"The Kildaire Road","author":"Rasheed A. Amini","publisher":"Triangle Editions","year":2024,"topic":"contemp","language":"en","audience":"adult","tint":"--tint-mustard","staffPick":true,"isNew":true,"description":"Essays from the first decade of a Cary masjid — potlucks, funerals, Friday khutbahs, and the slow work of building a community. Written by a longtime volunteer at The Light House Project.","status":"available"},
] as const;

export const run = internalMutation({
  args: {},
  handler: async (ctx) => {
    const existing = await ctx.db.query("books").first();
    if (existing) return "Catalog already seeded — skipping";
    for (const book of BOOKS) {
      await ctx.db.insert("books", { ...book });
    }
    return `Seeded ${BOOKS.length} books`;
  },
});
